before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8;
  - sudo apt-get install -qq gfortran-4.8
  - sudo apt-get install exuberant-ctags
  - sudo apt-get install libboost-dev
  - sudo apt-get install libplplot-dev
  - sudo apt-get install libboost-filesystem-dev

script: TOOL_CHAIN=TRAVIS make 
